# Generated by Django 2.2 on 2019-04-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190403_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='product',
            new_name='post',
        ),
    ]
